spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices

  cloud:
    config:
      import-check:
        enabled: false

  application:
    name: rating-service

  config:
    import: optional:configserver:http://localhost:8805


server:
  port: 8802


okta:
  oauth2:
    issuer: https://dev-71520996.okta.com/oauth2/default
    audience: api://default

