server:
  port: 8801

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Sujal
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    config:
      import-check:
        enabled: false

  application:
    name: hotel-service
  config:
    import: optional:configserver:http://localhost:8805


okta:
  oauth2:
    issuer: https://dev-71520996.okta.com/oauth2/default
    audience: api://default

